cmake_minimum_required(VERSION 3.24)

project(CUDA_Learning LANGUAGES CXX CUDA)

set(CMAKE_CUDA_ARCHITECTURES 89)

add_executable(vectorAdd vectorAdd.cu
    shared_memo.cu)
add_executable(hello hello.cu)
add_executable(matrixAdd matrixAdd.cu)
add_executable(copyMat copyMat.cu)
add_executable(matTranspose matTranspose.cu)
add_executable(matMul matMul.cu)

set_target_properties(vectorAdd PROPERTIES
    CUDA_SEPARABLE_COMPILATION ON
)
set_target_properties(hello PROPERTIES
    CUDA_SEPARABLE_COMPILATION ON
)
set_target_properties(matrixAdd PROPERTIES
    CUDA_SEPARABLE_COMPILATION ON
    RUNTIME_OUTPUT_DIRECTORY_DEBUG "${CMAKE_SOURCE_DIR}"
    RUNTIME_OUTPUT_DIRECTORY_RELEASE "${CMAKE_SOURCE_DIR}"
    RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO "${CMAKE_SOURCE_DIR}"
    RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL "${CMAKE_SOURCE_DIR}"
)
set_target_properties(copyMat PROPERTIES
    CUDA_SEPARABLE_COMPILATION ON
    RUNTIME_OUTPUT_DIRECTORY_DEBUG "${CMAKE_SOURCE_DIR}"
    RUNTIME_OUTPUT_DIRECTORY_RELEASE "${CMAKE_SOURCE_DIR}"
    RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO "${CMAKE_SOURCE_DIR}"
    RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL "${CMAKE_SOURCE_DIR}"
)
set_target_properties(matTranspose PROPERTIES
    CUDA_SEPARABLE_COMPILATION ON
    RUNTIME_OUTPUT_DIRECTORY_DEBUG "${CMAKE_SOURCE_DIR}"
    RUNTIME_OUTPUT_DIRECTORY_RELEASE "${CMAKE_SOURCE_DIR}"
    RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO "${CMAKE_SOURCE_DIR}"
    RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL "${CMAKE_SOURCE_DIR}"
)